% Set path to igpsoftware and define default globalAttributes
% 
% The Matlab path must be set to the main igpsoftware location, that
% contains the function 'igpimport' and toolbox configuration file.

disp('Set path to igpsoftware');
addpath('/home/hvandermarel/igp/igpsoftware'); 

% Define variable globalAttribDefault with default globalAttributes.
% Most main stm functions accept an option "globalAttrib" to set the 
% global attributes in the stm file, to use these default values you have 
% to do something like this in the top level script
%
%    options.globalAttrib = globalAttribDefault;  % Set global defaults
%    options.globalAttrib.comment = 'Goodmorning NAM'; % Optionally change a value
% 
% or specify the full structure if not of the defaults apply.

disp('Define variable "globalAttribDefault" with default global attributes');
globalAttribDefault = struct( ...
  'title'        , 'Integrated Geodetic Processing (IGP).' , ...
  'institution'  , 'Delft University of Technology, The Netherlands.' , ...
  'source'       , 'Nederlandse Aardolie Maatschappij (NAM) geodetic database.' , ...
  'technique'    , 'Levelling, GNSS, InSAR' , ...
  'history'      , ' ' , ...
  'references'   , 'TU Delft, NAM Integrated Geodetic Processing Report, 2020 (in preparation).' , ...
  'comment'      , ' ' , ...
  'Conventions'  , 'CF-1.6' , ...
  'featureType'  , 'timeSeries' , ... 
  'email'        , 'f.j.vanleijen@tudelft.nl, h.vandermarel@tudelft.nl' , ...
  'version'      , '0.3' , ...
  'terms_for_use', 'These data can be used freely for research purposes provided that the following source is acknowledged: Nederlandse Aardolie Maatschappij (NAM).' , ...
  'disclaimer'   , 'This data is made available in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.'  ...
);

